Repository Informasjonsforvaltning/fdk-portal, pull requests merged in 2023-01, with the labels that each got.

#1436 fix: bug - wrong color on open access lock icon
  src/images/icon-access-open-md-v2.svg
Labels: wcag

#1449 fix(details-page): main content overflow
  .npmrc
  package-lock.json
  src/components/dataset-distribution/components/summary/__tests__/styled.test.tsx
  src/components/dataset-distribution/components/summary/styled.ts
  src/components/details-page/components/details-page/styled.ts
Labels: bug, portal

#1466 fix(report-page): reduce spacing between components
  src/components/box-regular/styled.ts
  src/pages/report-page/components/conceptReport/conceptReport.component.tsx
  src/pages/report-page/components/dataserviceReport/dataserviceReport.component.tsx
  src/pages/report-page/components/datasetReport/datasetReport.component.tsx
  src/pages/report-page/components/informationModelReport/informationModelReport.component.tsx
  src/pages/report-page/styled.ts
Labels: bug, portal, responsive-design

#1488 fix: set line-height min val for paragraphs
  src/components/article-item/styled.ts
  src/components/article/components/article/styled.ts
  src/components/article/components/vimeo-video/styled.ts
  src/components/community/comments/components/composer/styled.ts
  src/components/community/comments/styled.ts
  src/components/concept-details-page/styled.ts
  src/components/details-page/components/banner/styled.ts
  src/components/infomodel-structure/model-element-list/styled.ts
  src/components/public-service-details-page/styled.ts
  src/components/search-hit/components/search-hit/styled.ts
  src/entrypoints/publishing/router/publishing/pages/publishing-page/styled.ts
  src/pages/cms-information-page/styled.ts
  src/pages/organizations/pages/dataset-page/styled.ts
Labels: wcag

#1502 fix: link missing a text alternative
  src/entrypoints/publishing/components/header/index.tsx
  src/entrypoints/publishing/router/publishing/pages/service-message-page/index.tsx
  src/pages/news-article-page-v2/news-article-page.tsx
Labels: frontend, wcag

#1504 fix(a11y): define global <p> line-heigh
  src/app/styles/common.ts
  src/components/article-item/styled.ts
  src/components/article/components/article/styled.ts
  src/components/article/components/vimeo-video/styled.ts
  src/components/community/comments/components/composer/styled.ts
  src/components/community/comments/styled.ts
  src/components/details-page/components/banner/styled.ts
  src/components/infomodel-structure/model-element-list/styled.ts
  src/components/public-service-details-page/styled.ts
  src/components/search-hit/components/search-hit/styled.ts
  src/entrypoints/publishing/router/publishing/pages/publishing-page/styled.ts
  src/pages/cms-information-page/styled.ts
  src/pages/organizations/pages/dataset-page/styled.ts
Labels: frontend, wcag

#1514 fix: set min line-height to 1.5 (unitless)
  src/app/styles/common.ts
  src/assets/designsystemet/scss/common.scss
  src/assets/designsystemet/scss/mixins.scss
  src/assets/designsystemet/scss/portal.scss
  src/assets/designsystemet/scss/typo.scss
  src/assets/fonts/icomoon.css
  src/components/community/container-header/styled.ts
  src/components/community/news-item/styled.ts
  src/components/community/post/styled.ts
  src/components/community/time-stamp/styled.ts
  src/components/dataset-distribution/components/summary/styled.ts
  src/components/details-page/components/banner/styled.ts
  src/components/details-page/components/details-page/styled.ts
  src/components/filter-box/filter-box.scss
  src/components/search-box/components/search-form/styled.ts
  src/components/search-hit-header/search-hit-header.scss
  src/components/truncated-text/styled.ts
  src/entrypoints/publishing/router/publishing/pages/publishing-page/styled.ts
  src/entrypoints/publishing/router/publishing/pages/service-message-page/styled.ts
  src/pages/organizations/pages/organization-page/styled.ts
  src/pages/report-page/publishers-select/publishers-select.scss
  src/pages/report-page/styled.ts
  src/pages/search-page/filter-pills/styled.ts
Labels: bug, frontend, wcag

#1517 fix: set min line-height to 1.5 (unitless)
  src/components/truncated-text/styled.ts
Labels: bug, frontend, wcag

#1507 Fix/por/empty container
  src/components/community/comments/index.tsx
  src/pages/organizations/pages/dataset-page/index.tsx
  src/pages/organizations/pages/datasets-page/index.tsx
Labels: bug, frontend, portal, wcag
